name: pydata-heidelberg
channels:
- conda-forge
dependencies:
- bqplot=0.12
- gpxpy=1.3.5
- ipycanvas
- ipyleaflet=0.11
- ipympl
- ipyvuetify=1.1
- jupyterlab-git
- jupyterlab=1
- jupyterlab_heroku
- matplotlib
- notebook>=6
- numpy
- pandas
- python=3.7
- pip
- plotly=4.4
- ptvsd
- seaborn
- srtm.py=0.3.4
- voila=0.1.20
- voila-gridstack=0.0.7
- voila-material=0.2.5
- voila-reveal=0.0.2
- voila-vuetify=0.2.2
- xeus-cling
- xeus-python=0.6
- xtensor=0.21

